[{
    "menuId": 1,
    "parentId": 0,
    "parentName": null,
    "name": "知识文档管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "fa fa-sitemap",
    "orderNum": 0,
    "open": null,
    "list": [{
        "menuId": 2,
        "parentId": 1,
        "parentName": null,
        "name": "文档上传",
        "url": "knowledge/knowledgeUpload.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-upload",
        "orderNum": 0,
        "open": null,
        "list": null
    }, {
        "menuId": 3,
        "parentId": 1,
        "parentName": null,
        "name": "文档审核",
        "url": "knowledge/knowledgeReview.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-search-plus",
        "orderNum": 0,
        "open": null,
        "list": null
    }
    , {
    	"menuId": 4,
    	"parentId": 1,
    	"parentName": null,
    	"name": "文档阅读",
    	"url": "pageview/index",
    	"perms": null,
    	"type": 1,
    	"icon": "fa fa-eye",
    	"orderNum": 0,
    	"open": null,
    	"list": null
    }
    , {
    	"menuId": 5,
    	"parentId": 1,
    	"parentName": null,
    	"name": "文档标签",
    	"url": "knowledge/knowledgeTag_New.html",
    	"perms": null,
    	"type": 1,
    	"icon": "fa fa-tags",
    	"orderNum": 0,
    	"open": null,
    	"list": null
    }
    ]
}, {
    "menuId": 33,
    "parentId": 0,
    "parentName": null,
    "name": "知识可视化",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "fa fa-italic",
    "orderNum": 0,
    "open": null,
    "list": [{
        "menuId": 37,
        "parentId": 33,
        "parentName": null,
        "name": "知识可视化",
        "url": "visualization/visualization.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-quora",
        "orderNum": 0,
        "open": null,
        "list": null
    },{
        "menuId": 38,
        "parentId": 33,
        "parentName": null,
        "name": "知识本体查看",
        "url": "ovo.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-search-plus",
        "orderNum": 0,
        "open": null,
        "list": null
    }]
}, {
    "menuId": 33,
    "parentId": 0,
    "parentName": null,
    "name": "语义搜索",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "fa fa-link",
    "orderNum": 0,
    "open": null,
    "list": [{
        "menuId": 37,
        "parentId": 33,
        "parentName": null,
        "name": "语义词典",
        "url": "semantics/semManagement.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-chain-broken",
        "orderNum": 0,
        "open": null,
        "list": null
    },{
        "menuId": 38,
        "parentId": 33,
        "parentName": null,
        "name": "语义搜索",
        "url": "semantics/semantics.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-search-plus",
        "orderNum": 0,
        "open": null,
        "list": null
    }]
}, {
    "menuId": 87,
    "parentId": 0,
    "parentName": null,
    "name": "逻辑推理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "fa fa-sign-in",
    "orderNum": 0,
    "open": null,
    "list": [{
        "menuId": 88,
        "parentId": 87,
        "parentName": null,
        "name": "逻辑推理",
        "url": "logic/index.html",
        "perms": null,
        "type": 1,
        "icon": "fa fa-quora",
        "orderNum": 0,
        "open": null,
        "list": null
    }]
}]